services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tracking
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build: .
    container_name: tracking
    depends_on:
      - db
    environment:
      DSN: postgres://postgres:postgres@db:5432/tracking?sslmode=disable
    command: >
      sh -c "
        while ! nc -z db 5432; do sleep 1; done;
        goose -dir internal/storage/migrations postgres \"$$DSN\" up;
        ./tracking
      "
    ports:
      - 8080:8080

volumes:
  db: